name: UI Selector & Visual Regression Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ui-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (React app)
        run: |
          cd development/clonedRepo/DevAutoRea/DevAutoRea
          npm install

      - name: Start React app in background
        run: |
          cd development/clonedRepo/DevAutoRea/DevAutoRea
          nohup npm run dev &

      - name: Wait for app to be ready
        run: |
          npx wait-on http://localhost:5173

      - name: Install dependencies (automation)
        run: |
          cd automation
          npm install

      - name: Extract baseline selectors if missing
        run: |
          cd automation
          if [ ! -f snapshots/baseline-selectors.json ]; then
            node extract-selectors.js snapshots/baseline-selectors.json
          fi

      - name: Run selector extraction and comparison
        run: |
          cd automation
          node extract-selectors.js snapshots/current-selectors.json
          node compare-selectors.js snapshots/baseline-selectors.json snapshots/current-selectors.json

      - name: Run BackstopJS visual regression tests
        run: |
          cd automation
          npx backstop test

      - name: Upload BackstopJS HTML report
        uses: actions/upload-artifact@v3
        with:
          name: backstop-report
          path: automation/backstop_data/html_report/